<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="HMI" Id="{f38ad59a-78b0-4789-8887-833d8ba3ce26}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK HMI
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	wDeviceAddress : WORD;
	wMotorAddress : WORD;
	bMotorPower : BOOL;
	bMotorOvercurrent : BOOL;
	rMotorTemperature : REAL;
	rMotorSpeed : REAL;
	rMotorPosition : REAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="displayValues" Id="{84f98107-3448-48e8-a3ae-474257ac1426}">
      <Declaration><![CDATA[METHOD displayValues
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{000d9a1f-0032-4f6d-a4be-ae7b9bc444e5}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="writeValuesToDevice" Id="{803aefaf-436f-4700-a6da-a452b20c6909}">
      <Declaration><![CDATA[METHOD writeValuesToDevice : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="HMI">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="HMI.displayValues">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="HMI.FB_init">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="HMI.writeValuesToDevice">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>